import Link from '@/components/datla/link';
import {ArrowUpRight,Building2,Users,Landmark,Award} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {palette,projectSpecimen} from '@/lib/datla';
export function Foundation(){return <main id="main">
<div className="review-bar"><div className="container"><span>PHASE 01 <span className="review-divider">/</span> DESIGN FOUNDATION</span><a href="/design-reference.png" target="_blank" rel="noreferrer">View supplied reference <ArrowUpRight size={14}/></a></div></div>
<section className="container foundation-intro"><div><p className="eyebrow">DATLA INFRA · VIJAYAWADA</p><h1>A foundation.<br/>Built on trust.</h1></div><p className="intro-note">The shared visual language of Datla Infra.<br/>Review the typography, colors, navigation,<br/>buttons and cards before the homepage.</p></section>
<section className="container specimen-grid" aria-label="Typography and card specimens"><div className="type-specimen"><p className="specimen-label">01 — TYPOGRAPHY & ACTIONS</p><h2>Building Trust.<br/>Creating Homes.<br/><span>Building Futures.</span></h2><p className="supporting">Premium Apartments.<br/>Thoughtfully Designed Communities.</p><div className="button-row"><Button asChild className="datla-button"><Link href="/projects">Explore Projects</Link></Button><Button asChild className="datla-button outline-button"><Link href="/contact">Contact Us</Link></Button></div><div className="font-note"><span>Playfair Display <small>Headings</small></span><span>Poppins <small>Body & interface</small></span></div></div><div className="card-specimen"><p className="specimen-label">02 — PROJECT CARD</p><article className="project-card"><div className="reference-crop" role="img" aria-label="Subhadra Residency architecture cropped from the supplied design reference"/><div className="project-card-body"><h3>{projectSpecimen.name}</h3><p>{projectSpecimen.detail}</p><p className="project-status">{projectSpecimen.status}</p><Button asChild className="datla-button outline-button"><Link href={projectSpecimen.href}>View Details</Link></Button></div></article><p className="specimen-caption">Visual specimen · reference image crop</p></div></section>
<section className="container palette-section" aria-labelledby="palette-title"><div className="section-heading"><h2 id="palette-title">The color palette</h2><span>03 — BRAND COLORS</span></div><div className="palette-grid">{palette.map(([name,hex])=><div className="swatch" key={hex}><div style={{background:hex}}/><h3>{name}</h3><span>{hex}</span></div>)}</div></section>
<section className="icon-strip" aria-label="Icon and metric specimens"><div className="container metric-grid">{[{Icon:Building2,n:'2',label:'Completed Projects'},{Icon:Users,n:'70+',label:'Happy Families'},{Icon:Landmark,n:'50+',label:'Flats Under Construction'},{Icon:Award,n:'5+',label:'Years of Excellence'}].map(({Icon,n,label})=><div className="metric" key={label}><div><Icon aria-hidden="true"/><span>{n}</span></div><p>{label}</p></div>)}</div></section>
<section className="container review-end"><div><p className="eyebrow">PHASE 01 REVIEW</p><h2>The essentials, in place.</h2><p>Shared layout and page routes are ready. The homepage is Phase 2.</p></div><Button asChild className="datla-button light-outline"><a href="/design-reference.png" target="_blank" rel="noreferrer">Open Design Reference <ArrowUpRight/></a></Button></section>
</main>}
